### PR TITLE
Codes

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
Thank You

**Comment by dpallagolla** [comment]
If you are interested in contributing further, let me know, I will add you
as a contributor to the repo.

**Comment by ghost** [comment]
It was my first day of contribution yesterday. So i dont know exactly what 'add you
as a contributor to the repo' means.

**Comment by dpallagolla** [comment]
As of now you cloned my repo and added code and sent a pull request right,
you can directly check-in code to my repo if you are added as a
contributor, you don't have to send further pull requests

**Comment by ghost** [comment]
Ok then please add

**Comment by ghost** [comment]
Hi. There is one repository in my profile
 project-Euler
Forked from dpallagolla/project-Euler

which says 'This branch is 6 commits behind dpallagolla:master.' 
Is this repo of any use now as you made me a contributor?
If yes then how can i merge so that the changes i made in one are automatically done in the other?

**Comment by dpallagolla** [comment]
The repo is of no use now, if you again want to sync it with my repo,
you'll have to send another pull request, you'll have to keep doing this if
you continue to check-in to the repo in your account
Instead you can dump it and check-in to mine directly
I have temporarily paused solving problems but I hope to resume soon!

**Pull request merged**
